### ISSUE TITLE
Upgrade CE containers to use latest packages

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-package#14]
We need to run package manager in all containers to make sure that CE based on latest packages.
After that we need to run commands like this `yum clean all` to clean caches and remove bash history.

**Comment by yurem** [comment]
We also need to upgrade:
node-v6.9.1-linux-x64.tar.xz --> node-v8.10.0-linux-x64.tar.xz (https://nodejs.org/dist/v9.9.0/node-v9.9.0-linux-x64.tar.xz)
server-jre-8u112-linux-x64.tar.gz --> server-jre-8u162-linux-x64.tar.gz (http://www.oracle.com/technetwork/java/javase/downloads/server-jre8-downloads-2133154.html)
jetty-distribution-9.3.15.v20161220.tar.gz --> jetty-distribution-9.4.9.v20180320.tar.gz (http://central.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.9.v20180320/jetty-distribution-9.4.9.v20180320.tar.gz)

**Comment by adrian-gluu** [comment]
We upgraded it as Yura requested:
 node-v8.10.0-linux-x64.tar.xz
server-jre-8u162-linux-x64.tar.gz 
jetty-distribution-9.4.9.v20180320.tar.gz

**Comment by adrian-gluu** [comment]
In this new built 6-beta2, we upgraded all the apps:
https://repo.gluu.org/ubuntu/pool/main/trusty-devel/gluu-server-3.1.3_1.6.BETA3~trusty+Ub14.04_amd64.deb
https://repo.gluu.org/centos/testing/gluu-server-3.1.3-1-6.BETA3.centos6.x86_64.rpm
