### ISSUE TITLE
[Debian8] Port address(es) :443 already in use

### ISSUE THREAD

**Issue by peppelinux** [GluuFederation/community-edition-package#16]
I installed today Gluu 3.1.3 on a Debian8 netinst and I found this exeption on its first run.
I checked the init script in this repository then I faced that $ symbols was missing in the Debian's packaged release.

````
PORTS=`netstat -tunpl | awk '{ print $4 }' |grep -Eoh ':(80|443|8080|8081|8082|8083|8084|8085|8086|8090|8091|1389|1689|11211)'`
````
to

````
PORTS=`netstat -tunpl | awk '{ print $4 }' |grep -Eoh ':(80|443|8080|8081|8082|8083|8084|8085|8086|8090|8091|1389|1689|11211)$'`
````

this ticket is just a reminder for you to update the debs.

**Comment by nikdavnik** [comment]
Issue have been fixed. Thanks
