### ISSUE TITLE
Put passport modules archive passport-node_modules.tar.gz into /opt/gluu/dist

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-package#18]
It's needed to support offline installation: https://github.com/GluuFederation/community-edition-setup/issues/460

We can add one additional step in CE building. We can do:
1. Unzip passport into temp build folder,
2. Run npm install, check exit code to make sure that we downloaded all modules.
3. Create tar.gz and put into /opt/gluu/dist/

Alternative solution is to build this archive manually before final release.

**Comment by mbaser** [comment]
I implemented with 3.1.3/update.py

**Comment by nikdavnik** [comment]
Implemented
