### ISSUE TITLE
Add GLIBC_2.14 to centOS6 package

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/community-edition-package#19]
Steps:
1. Download the pkg from our repo
2. yum install the package
3. Follow the docs and run the setup
4. Choose **everything** to be installed  + OpenLDAP

Expected: After adding the hostname to /etc/hosts, the user should connect to ce.

Actual: There's a 503 error displayed, most likely because of the lack of GLIBC_2.14 in the system (please refer to the logs). 
Let me know if this issue should be moved to another project.

[2018_08_30.jetty.log.tar.gz](https://github.com/GluuFederation/community-edition-package/files/2335177/2018_08_30.jetty.log.tar.gz)
[failed_solserver_restart.txt](https://github.com/GluuFederation/community-edition-package/files/2335187/failed_solserver_restart.txt)

Tested with **gluu-server-3.1.4-1-Beta2.centos6.x86.**

**Comment by mbaser** [comment]
Outdated
