### ISSUE TITLE
Method which detect if all required ports are free not works well

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-package#24]
According to this [issue ](https://support.gluu.org/installation/6160/gluu-server-314-httpshostnameidentityerror-failed-to-execute-registration-script/)it's possible to start/login/install CE under RHEL 7 even if port 8081 is busy by another process:

**Comment by ganesh-at-wiw** [comment]
@yurem installation success is fine, but service start was NOT successful.


15:08:07 10/18/18 Running: /usr/bin/systemctl enable httpd
15:08:07 10/18/18 Running: /usr/bin/systemctl start httpd
15:08:07 10/18/18 Running: /usr/bin/systemctl stop opendj
15:08:13 10/18/18 Run: /usr/bin/systemctl stop opendj with result code: 0
15:08:13 10/18/18 Running: /usr/bin/systemctl start opendj
15:08:20 10/18/18 Run: /usr/bin/systemctl start opendj with result code: 0
15:08:20 10/18/18 Running: /usr/bin/systemctl start oxauth

> 15:08:36 10/18/18 Run: /usr/bin/systemctl start oxauth with result code: 1


15:08:36 10/18/18 Running: /usr/bin/systemctl start identity
15:08:57 10/18/18 Run: /usr/bin/systemctl start identity with result code: 0
15:08:57 10/18/18 Running: /usr/bin/systemctl start passport
15:08:57 10/18/18 Run: /usr/bin/systemctl start passport with result code: 0
15:08:57 10/18/18 Saving properties to ./setup.properties.last
-bash-4.2#


This is the initially posted log.

**Comment by ganesh-at-wiw** [comment]
The way we check the ports in use is:
PORTS=`netstat -tunpl | awk '{ print $4 }' |grep -Eoh ':(80|443|8080|8081|8082|8083|8084|8085|8086|8090|8091|1389|1689|11211)$'`

Now here are two scenarios:
1. We do not want to allow services to run at all on restricted ports if these ports are in use already. Doesn't matter whether these run on tcp/udp/tcp6.
2. We can allow services running on tcp6 to co-exist with our services running at tcp.
Below is an example from my VM where apache runs on port 80 at tcp6 on main VM and on normal tcp ipv4 inside chroot.

```
root@vsurpr0002:~# netstat -ntaulp|egrep -e "80"
tcp6       0      0 :::80                   :::*                    LISTEN      3450/apache2    
tcp6       0      0 :::80                   :::*                    LISTEN      2255/apache2    
tcp6       0      0 127.0.0.1:8081          :::*                    LISTEN      3038/java       
tcp6       0      0 127.0.0.1:8082          :::*                    LISTEN      3193/java       
udp6       0      0 fe80::a00:27ff:fed0:123 :::*                                1817/ntpd     

```
For allowing the second choice I simply filtered tcp6 from our test as below:

PORTS=`netstat -tunpl | grep -v tcp6 | awk '{ print $4 }' |grep -Eoh ':(80|443|8080|8081|8082|8083|8084|8085|8086|8090|8091|1389|1689|11211)$'`

So, let's decide what we want to use out of two choices.

**Comment by ganesh-at-wiw** [comment]
Also, if we choose to go with first choice, we do not need to do anything.

**Comment by yurem** [comment]
I think first approach is good one. I think so because tcp6 supports both IPv6 and IPv4 protocols.
It looks like customer installed service into host which uses 8081 after CE install.
