### ISSUE TITLE
Ub18Server: can't install CE3.1.4

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/community-edition-package#25]
@nikdavnik and @adrian-gluu, it's impossible to install CE3.1.4 using the following commands:
```
echo "deb https://repo.gluu.org/ubuntu/ bionic-devel main" > /etc/apt/sources.list.d/gluu-repo.list
curl https://repo.gluu.org/ubuntu/gluu-apt.key | apt-key add -
apt-get update
apt-get install gluu-server-3.1.4
```

The console output is the following:
<img width="793" alt="ub18_broken_pkg" src="https://user-images.githubusercontent.com/38302725/48966848-5e880580-f02c-11e8-975d-e196050d4bc9.png">

**Please provide a fix and exact steps for both desktop and server installations, as well as enhance the error messages for better UX.**

**Comment by nikdavnik** [comment]
please use those instruction to install ubuntu 18 package

```
echo “deb https://repo.gluu.org/ubuntu/ bionic-devel main” > /etc/apt/sources.list.d/gluu-repo.list
echo “deb https://repo.gluu.org/ubuntu/ bionic universe” >> /etc/apt/sources.list
echo “deb http://archive.ubuntu.com/ubuntu bionic-updates universe >> /etc/apt/sources.list
curl https://repo.gluu.org/ubuntu/gluu-apt.key | apt-key add -
apt-get update
apt-get install gluu-server-3.1.4
```

**Comment by natt-tester** [comment]
echo "deb https://repo.gluu.org/ubuntu/ bionic-devel main" > /etc/apt/sources.list.d/gluu-repo.list
echo "deb http://archive.ubuntu.com/ubuntu/ bionic universe" >> /etc/apt/sources.list
echo "deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe" >> /etc/apt/sources.list
curl https://repo.gluu.org/ubuntu/gluu-apt.key | apt-key add -
apt-get update
apt-get install gluu-server-3.1.4
