### ISSUE TITLE
DNS resolution not work in Debin 9 package

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-package#29]

**Comment by adrian-gluu** [comment]
we should add google dns in resolv.conf and rebuild, lets try that in a new build

**Comment by adrian-gluu** [comment]
working on a new build using google dns inside of the chroot

**Comment by ganesh-at-wiw** [comment]
Hi @adrian-gluu 
The problem stems from the fact that the debian9 machine has hostname: /etc/hostname as debian9.
Please make it: localhost and the problem should be corrected.

I've just tested it on fresh install of debian9.

**Comment by ganesh-at-wiw** [comment]
I think my problem is not exactly about DNS resolution, but about apache2 not starting. My solution applies to that.

**Comment by yurem** [comment]
@ganesh-at-wiw I changed hostname in CE to `localhost` inside `/etc/hostname`. But this not help to resolve it.

```
root@debian:~# gluu-serverd-3.1.5 login
...
root@localhost:~# cat /etc/hostname
localhost
root@localhost:~# ping google.com
ping: google.com: No address associated with hostname
root@localhost:~#
```

What I missed there?

**Comment by yurem** [comment]
@adrian-gluu I think final package should work without public DNS server like 8.8.8.8

**Comment by mbaser** [comment]
Still has issue:
```
# cd /etc
# ls -al resolv.conf 
lrwxrwxrwx 1 root root 35 Jan 13 11:25 resolv.conf -> /var/run/NetworkManager/resolv.conf
root@debian9:/etc# cat /var/run/NetworkManager/resolv.conf
# cat: /var/run/NetworkManager/resolv.conf: No such file or directory
```

I solved with:
```
# unlink resolv.conf
```
On the outside of the container:
```
$ sudo scp /etc/resolv.conf /opt/gluu-server-3.1.5/etc
```
Inside of the container:
```
# ping www.googl.com
PING www.googl.com (216.58.212.35) 56(84) bytes of data.
64 bytes from sof02s18-in-f3.1e100.net (216.58.212.35): icmp_seq=1 ttl=51 time=37.6 ms
64 bytes from sof02s18-in-f3.1e100.net (216.58.212.35): icmp_seq=2 ttl=51 time=37.9 ms
```

**Comment by adrian-gluu** [comment]
sorted this issue in this new build:
https://repo.gluu.org/debian/pool/main/stretch-testing/gluu-server-3.1.5_1-9~Db9stretch_amd64.deb

**Comment by mbaser** [comment]
Not worked for me

![screenshot_2019-01-14_01-34-05](https://user-images.githubusercontent.com/6398752/51091513-88dc8080-179c-11e9-84af-10bc08ca424d.png)

Please recheck.

**Comment by ganesh-at-wiw** [comment]
Hello guys
these are two things:
1. Public DNS included in resolv.conf
2. hostname to be localhost

The first one resolves the actual issue, i.e DNS not resolving.
The second one resolves the apache not starting issue.

I hope I'm clear now.

**Comment by ganesh-at-wiw** [comment]
Confirmed resolved.
