### ISSUE TITLE
Add comand to configure host system

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-package#32]
In CE we can't apply OS tuning in chroot/systemd. We need to do in host. As result we can create helper script for administrator which do performance updates. Couchbase specific changes @mbaser prepared already: https://github.com/GluuFederation/community-edition-setup/commit/a4859f0465430821f5f933364743015641eb903c We can reuse them in new script.

**Comment by ganesh-at-wiw** [comment]
Do you think @yurem we can add function in init script itself like:
service gluu-server-3.1.6 set_os_tuning
?

**Comment by ganesh-at-wiw** [comment]
To start with I added:
https://github.com/GluuFederation/community-edition-package/commit/159b00d9be50ccd73b8d8dcb16af5506d3301e62#diff-5dfd552a9169b091ada6d476a7295596

**Comment by mbaser** [comment]
It seems 4.3.x versions don't have this feature
```
# gluu-serverd set_os_tuning
Usage: /usr/sbin/gluu-serverd {enable|start|restart|ready|login|stop|disable|status|version}
```

**Comment by mbaser** [comment]
Ganesh modified gluu-serverd to include `tune_os` option. The file is located at
https://raw.githubusercontent.com/GluuFederation/community-edition-package/master/package/initd/gluu-serverd
 @nikdavnik Can you use this file as `/sbin/gluu-serverd` for CE container builds?

**Comment by mbaser** [comment]
Done
