### ISSUE TITLE
Update gluu-server init script to accommodate systemctl

### ISSUE THREAD

**Issue by ganesh-at-wiw** [GluuFederation/community-edition-package#34]
Update gluu-server init script to accommodate systemctl to use similar commands for starting/stopping services.

**Comment by ganesh-at-wiw** [comment]
I and Mustafa have discussed and doing some changes in setup.py.

**Comment by mbaser** [comment]
closed by commit https://github.com/GluuFederation/community-edition-setup/commit/15b1f3280dff51d3a986bc3085591d576ec6bd93
