### ISSUE TITLE
Use Wildcard for Apache virtual host setting

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-package#4]
We use the IP address for virtual host config in Apache in `https_gluu.conf` and `httpd_2.4.conf`

For example:

```
<VirtualHost  %(ip)s:80>
        ServerName %(hostname)s
        Redirect  / https://%(hostname)s/
        DocumentRoot "/var/www/html/"
</VirtualHost>

<VirtualHost %(ip)s:443>
        DocumentRoot "/var/www/html/"
        ServerName %(hostname)s:443
```

I think it would be better for default config to use `*:80` and `*:443`  

Customers ultimately may want to adjust the Apache httpd config, but the wildcard config will work in more situations, and I think fits with the goal for CE ease of deployment.

**Comment by ganesh-at-wiw** [comment]
yes for sure.

**Comment by ganesh-at-wiw** [comment]
https://github.com/GluuFederation/community-edition-setup/commit/0c1f80a8fab47251566e9be476728892a08080db#diff-03977dfe18120f823fed2a0408021ef1
