### ISSUE TITLE
gitlab-ci for packaging (replace jenkings)

### ISSUE THREAD

**Issue by adrian-gluu** [GluuFederation/community-edition-package#42]
we need to spin up a new VM and install gitlab-ci automate the whole build process for packaing it will be better faster and NO MORE build VMs also a GIT for keep our packaging sources and WIKI to document anythig realated with packaging TEAM

**Comment by adrian-gluu** [comment]
@ganesh-at-wiw ca you spin up a pkg-ci.gluu.org

**Comment by adrian-gluu** [comment]
i will hadle the setup process course you can contribute ganesh together with davit

**Comment by nynymike** [comment]
We have a big investment in Jenkins. Start a wiki page, propose the advantage, and we can discuss it with the developers.  Adding a bunch of work for Yura is not desirable right now. So the advantage of moving to Gitlab-ci has to be significant.
