### ISSUE TITLE
3.1.x to 4.x upgrade / CR broken / o=site DN lost

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-package#45]
Upgraded customer's 3.1.6 to 4.0, which eventually removed two main entries which are important to run Cache refresh. Those entries are: 

- `o=site`: 

```
dn: o=site
changetype: add
objectClass: organization
objectClass: top
o: site
```
- `ou=people,o=site`: 

```
dn: ou=people,o=site
objectClass: organizationalUnit
objectClass: top
ou: people
```

Cache refresh can't run without these two entries.

**Comment by mbaser** [comment]
I made two commits related to cache refresh:

https://github.com/GluuFederation/community-edition-package/commit/a7e11821b6db3c48418fff15d3d66e42d83a3f17#diff-f71356ee47b11d965cddb7e8b4e5f42f

https://github.com/GluuFederation/community-edition-package/commit/d0a7b74d686259eae4e1aaf87696b929bd4db5b6#diff-f71356ee47b11d965cddb7e8b4e5f42f

Think this should fix o=site issue.

Please don’t use pre-packaged static upgrade script. Instead use online:
```
# wget https://raw.githubusercontent.com/GluuFederation/community-edition-package/master/update/4.0/update.py
# python update.py -o
```

**Comment by mbaser** [comment]
Implemented in https://github.com/GluuFederation/community-edition-package/commit/76307330e77cb5860a66a81f17cc09834351b370
