### ISSUE TITLE
Update 4.0 script missing attribute bug

### ISSUE THREAD

**Issue by moabu** [GluuFederation/community-edition-package#48]
Running [script](https://github.com/GluuFederation/community-edition-package/blob/master/update/4.0/update.py) Upgrading from 3.1.5 to 4.0 caused error due to missing attribute `update_jython`

```bash
Upgrading Java
Traceback (most recent call last):
File “update.py”, line 2065, in <module>
updaterObj.update_jython()
AttributeError: GluuUpdater instance has no attribute ‘update_jython’
```

**Comment by mbaser** [comment]
Fixed in commit a7b70a815ba9179f9431b2a51d181bb67563ef24
