### ISSUE TITLE
Upgrade to 4.2.1 must fill existing oxAuthSessionId entries with `sid` attribute with random uuid

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/community-edition-package#49]
There is new `sid` attribute added to oxAuthSessionId entity. This attribute must be populated with random uuid.

It comes from https://github.com/GluuFederation/oxAuth/issues/1458

**Comment by mbaser** [comment]
Even after adding `sid` to session entries, sessions are not retrained after upgrade, i.e., users logged in to gluu before upgrade can't continue after upgrade. For this reason, upgrade script deletes session entries on couchbase and modifies (add sid) on ldap.
Closing the issue until we have another idea.
