### ISSUE TITLE
Prepare script to reconfigure build folder for specified version

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-package#5]
Our init/systemd script is generic for all CE versions already. It has variable `GLUU_VERSION` which allows to specify which version to start. This new script should update this variable and version in other places if need.

**Comment by ganesh-at-wiw** [comment]
Created branches 3.0.0, 3.0.1, 3.0.2, 3.1.0 and Adrian fixed fetch sources.
All set now.
