### ISSUE TITLE
Fake gluu-serverd is does not start/stop oxd-server

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/community-edition-package#50]
For nochroot package we have fake gluu-serverd which starts/stops services via systemctl: https://github.com/GluuFederation/community-edition-package/blob/master/ce-host/4.2.1/gluu-serverd

This script does not start/stop oxd-server

**Comment by ganesh-at-wiw** [comment]
https://github.com/GluuFederation/community-edition-package/commit/e1609eb63df6f2c3ce4eb7fb9d1c95f6eb982043#diff-4666e363ca9582e1cae42ffedbe5d110
