### ISSUE TITLE
4.2 to 4.3 Upgrade script

### ISSUE THREAD

**Issue by HemantKMehta** [GluuFederation/community-edition-package#53]
We have added a new feature in Gluu Server 4.3 to add and retain custom claims in access tokens https://github.com/GluuFederation/oxAuth/wiki/Retain-access-token-claim.
 
Time to time we also get demand for such support in previous versions e.g. Gluu Server 4.2. This is in reference to Ticket#9463 (https://support.gluu.org/access-management/9463/add-custom-claims-to-jwt-access-token/). 

Once we release the Gluu Server 4.3 we need to develop the upgrade script for Gluu server 4.2 to 4.3.

**Comment by mbaser** [comment]
@HemantKMehta I need step by step guide. Please give example of old entry and end new entry together with how I can convert old entry to new entry.
